// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID       string `gorm:"column:id;type:text;primaryKey" json:"id"`
	Name     string `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Email    string `gorm:"column:email;type:character varying(100);not null" json:"email"`
	Password string `gorm:"column:password;type:text;not null" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
